name: solarforecast
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0=py311hca03da5_0
  - anyio=4.2.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - babel=2.11.0=py311hca03da5_0
  - beautifulsoup4=4.12.3=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h313beb8_0
  - bokeh=3.4.1=py311hb6e6a13_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - branca=0.6.0=py311hca03da5_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py311h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=h302bd0f_5
  - catalogue=2.0.10=py311hca03da5_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.16.0=py311h80987f9_1
  - cfitsio=3.470=h7f6438f_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpathlib=0.16.0=py311hca03da5_1
  - colorama=0.4.6=py311hca03da5_0
  - comm=0.2.1=py311hca03da5_0
  - confection=0.1.4=py311hb6e6a13_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py311h313beb8_1
  - cython-blis=0.7.9=py311hb9f6ed7_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311hca03da5_0
  - et_xmlfile=1.1.0=py311hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h313beb8_0
  - fiona=1.9.5=py311h7aedaa7_0
  - folium=0.14.0=py311hca03da5_0
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - freexl=2.0.0=ha3de405_0
  - fuzzywuzzy=0.18.0=py311hca03da5_0
  - gdal=3.6.2=py311h950983f_6
  - gensim=4.3.3=py311h7aedaa7_0
  - geopandas=0.14.2=py311hca03da5_0
  - geopandas-base=0.14.2=py311hca03da5_0
  - geos=3.9.1=hc377ac9_1
  - geotiff=1.7.0=h41f0982_3
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - h11=0.14.0=py311hca03da5_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - httpcore=1.0.2=py311hca03da5_0
  - httpx=0.27.0=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - ipykernel=6.28.0=py311hca03da5_0
  - ipython=8.27.0=py311hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.19.1=py311hca03da5_0
  - jinja2=3.1.4=py311hca03da5_0
  - joblib=1.4.2=py311hca03da5_0
  - jpeg=9e=h80987f9_3
  - json-c=0.16=h1a28f6b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=7.4.9=py311hca03da5_0
  - jupyter_core=5.7.2=py311hca03da5_0
  - jupyter_events=0.10.0=py311hca03da5_0
  - jupyter_server=2.14.1=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab=4.2.5=py311hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311hca03da5_0
  - kealib=1.5.0=hba2eb73_1
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.6.2=h51eea9d_6
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libkml=1.3.0=hc4d7c42_7
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.20=h02f6b3c_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialindex=1.9.3=hc377ac9_0
  - libspatialite=5.1.0=h3e2df84_1
  - libssh2=1.11.0=h3e2b118_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.13.1=h0b34f26_2
  - libzip=1.8.0=h62fee54_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mapclassify=2.5.0=py311hca03da5_0
  - markdown-it-py=2.2.0=py311hca03da5_1
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib=3.7.2=py311hca03da5_0
  - matplotlib-base=3.7.2=py311h7aedaa7_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mdurl=0.1.0=py311hca03da5_0
  - minizip=4.0.3=ha89c15f_0
  - mistune=2.0.4=py311hca03da5_0
  - murmurhash=1.0.7=py311h313beb8_0
  - nb_conda_kernels=2.3.1=py311hca03da5_0
  - nbclassic=1.1.0=py311hca03da5_0
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - networkx=3.3=py311hca03da5_0
  - nltk=3.9.1=py311hca03da5_0
  - notebook=6.5.7=py311hca03da5_0
  - notebook-shim=0.2.3=py311hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.5.2=h54b8e55_0
  - openpyxl=3.1.5=py311h80987f9_0
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.4.0=py311hca03da5_0
  - packaging=24.1=py311hca03da5_0
  - pandas=2.2.2=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.6=py311hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h80987f9_0
  - pip=24.2=py311hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - pooch=1.8.2=py311hca03da5_0
  - poppler=22.12.0=h52f4003_3
  - poppler-data=0.4.11=hca03da5_1
  - preshed=3.0.6=py311h313beb8_0
  - proj=9.3.1=h805f6d4_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py311hca03da5_0
  - pydantic-core=2.20.1=py311hf0e4da2_0
  - pygments=2.15.1=py311hca03da5_1
  - pyparsing=3.0.9=py311hca03da5_0
  - pyproj=3.6.1=py311h041c639_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.9=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - python-levenshtein=0.12.2=py311h80987f9_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=24.0.1=py311h80987f9_0
  - qhull=2020.2=h48ca7d4_2
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - regex=2024.9.11=py311h80987f9_0
  - requests=2.32.3=py311hca03da5_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rich=13.9.4=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - rtree=1.0.1=py311hca03da5_0
  - scikit-learn=1.1.3=py311h313beb8_1
  - scipy=1.10.0=py311he704c8e_1
  - seaborn=0.13.2=py311hca03da5_0
  - send2trash=1.8.2=py311hca03da5_0
  - setuptools=72.1.0=py311hca03da5_0
  - shapely=2.0.5=py311h3713c0e_0
  - shellingham=1.5.0=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sklearn-pandas=2.2.0=py311hca03da5_0
  - smart_open=5.2.1=py311hca03da5_0
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - spacy=3.7.2=py311h30ceab6_0
  - spacy-legacy=3.0.12=py311hca03da5_0
  - spacy-loggers=1.0.4=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - srsly=2.4.8=py311h313beb8_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.2=py311hb9f6ed7_0
  - terminado=0.17.1=py311hca03da5_0
  - thinc=8.2.2=py311h30ceab6_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tiledb=2.3.3=hb4a6b97_3
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.1=py311h80987f9_0
  - traitlets=5.14.3=py311hca03da5_0
  - typer=0.9.0=py311hca03da5_0
  - typing-extensions=4.11.0=py311hca03da5_0
  - typing_extensions=4.11.0=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - uriparser=0.9.7=h80987f9_0
  - urllib3=2.2.2=py311hca03da5_0
  - wasabi=0.9.1=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.3.4=py311hca03da5_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=1.8.0=py311hca03da5_0
  - wheel=0.44.0=py311hca03da5_0
  - xerces-c=3.2.4=h313beb8_1
  - xyzservices=2022.9.0=py311hca03da5_1
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - arrow==1.3.0
      - binaryornot==0.4.4
      - blosc2==3.10.2
      - cftime==1.6.5
      - chardet==5.2.0
      - cloudpickle==3.1.1
      - cookiecutter==2.6.0
      - cookiecutter-data-science==2.3.0
      - coverage==7.6.4
      - dask==2025.10.0
      - dotenv==0.9.9
      - einops==0.8.1
      - empath==0.89
      - en-core-web-sm==3.7.1
      - filelock==3.20.0
      - fontawesomefree==6.6.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - funcy==2.0
      - fuzzy==1.2.2
      - h5py==3.15.1
      - importlib-metadata==8.7.0
      - iniconfig==2.0.0
      - jellyfish==1.1.2
      - lib==4.0.0
      - lightning-utilities==0.15.2
      - locket==1.0.0
      - loguru==0.7.3
      - metaphone==0.6
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - ndindex==1.10.0
      - netcdf4==1.7.3
      - numexpr==2.14.1
      - partd==1.4.2
      - phonetics==1.0.5
      - plotly==5.24.1
      - pluggy==1.5.0
      - pprintpp==0.4.0
      - propcache==0.4.1
      - pvlib==0.13.1
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pycountry-convert==0.7.2
      - pyldavis==3.4.1
      - pytest==8.3.3
      - pytest-cov==6.0.0
      - pytest-mock==3.14.0
      - python-dotenv==1.1.1
      - python-louvain==0.16
      - python-slugify==8.0.4
      - pytorch-lightning==2.5.5
      - pywaffle==1.1.1
      - repoze-lru==0.7
      - sympy==1.14.0
      - tables==3.10.2
      - tenacity==9.0.0
      - text-unidecode==1.3
      - textblob==0.18.0.post0
      - tiktoken==0.8.0
      - tomlkit==0.13.3
      - toolz==1.1.0
      - torch==2.8.0
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spatiotemporal==0.9.5
      - torchmetrics==1.8.2
      - tqdm==4.67.0
      - tsl==2.0
      - types-python-dateutil==2.9.0.20250822
      - vadersentiment==3.3.2
      - wordcloud==1.9.4
      - xarray==2025.10.1
      - xlrd==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/solarforecast
