# config/preprocessing.yaml
date_range:
  start: "2023-01-01 00:00:00"
  end: "2023-01-31 23:59:59"

frequency: "10min"   # fréquence finale à imposer pour resampling

windows:
  past_timesteps: 12      # e.g. 12 * 10min = 2h
  future_timesteps: 24    # e.g. 24 * 10min = 4h
