batch_size: 64
data:
  ground_value_col: irradiance_csi
  sat_time_col: time
  sat_value_col: irradiance_csi
  target_station: PUY
date_range:
  end: '2023-12-31 23:59:59'
  start: '2023-01-01 00:00:00'
frequency: 10min
future_timesteps: 6
model:
  fusion:
    activation1: relu
    activation2: gelu
    activation3: relu
    dropout: 0.3
    name: FusionModel
    x1: 64
    x2: 32
    x3: 16
  ground:
    activation: selu
    add_backward: false
    add_embedding_before: []
    cached: false
    emb_size: 0
    exog_size: 0
    graph_layers: 3
    hidden_size: 128
    input_size: 1
    name: TimeThenGraphIsoModel
    nodes: 6
    noise_mode: lin
    norm: none
    output_size: 128
    root_weight: true
    time_layers: 3
    time_skip_connect: true
    use_local_weights: null
  satellite:
    attn_dim: 32
    conv1_channels: 32
    conv2_channels: 64
    feature_dim: 64
    head_hidden_dim: 32
    input_channels: 1
    kernel_size: 3
    name: SatelliteCNN
    pool_size: 2
    temporal_layers: 2
    use_temporal_encoder: true
past_timesteps: 18
